baseURL = "https://lainz.github.io/cuentos-gra/"
languageCode = "es-ar"
title = "Cuentos de GRA"
theme = "ananke"
publishDir = "docs"
googleAnalytics = "UA-53516302-4"

[params]
featured_image = "/images/mariposa-luna.png"
recent_posts_number = 100